name: pip-install-check-dagster-testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - dagster_university/dagster_testing/pyproject.toml

jobs:
  check:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/template-pip-install-check.yml
    with:
      working_directory: ./dagster_university/dagster_testing
      module_name: dagster_testing

