name: quality-check-dagster-and-etl

on:
  schedule:
    - cron: "0 0 * * 0"

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - dagster_university/dagster_and_etl/**

jobs:
  check:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/template-quality-check.yml
    with:
      working_directory: ./dagster_university/dagster_and_etl
      # TODO:  Disable integration tests from GHA
      # postgres image has no windows/amd64
      windows_pytest_cmd: uv run pytest dagster_and_etl_tests -v -m "not integration"